
export const FEATURE_ORDER = [
  'policyType',
  'entryAge',
  'sumInsured',
  'premium',
  'hospitalization',
  'prePostHosp',
  'dayCare',
  'restoreBenefit',
  'cumulativeBonus',
  'chronicDisease',
  'maternity',
  'newbornCover',
  'wellness',
  'opdCover',
  'otherBenefits',
  'waitingPeriods',
  'exclusions',
  'usps',
];

export const FEATURE_LABELS: { [key: string]: string } = {
  policyType: 'Policy Type',
  entryAge: 'Entry Age',
  sumInsured: 'Sum Insured (SI) Options',
  premium: 'Premium Range',
  hospitalization: 'Hospitalization',
  prePostHosp: 'Pre/Post-Hosp.',
  dayCare: 'Day Care',
  restoreBenefit: 'Restore Benefit',
  cumulativeBonus: 'Cumulative / No-Claim Bonus',
  chronicDisease: 'Chronic Disease',
  maternity: 'Maternity',
  newbornCover: 'Newborn Cover',
  wellness: 'Wellness Program',
  opdCover: 'OPD Cover',
  otherBenefits: 'Other Benefits',
  waitingPeriods: 'Waiting Periods',
  exclusions: 'Brief Exclusions',
  usps: 'Unique Selling Propositions (USPs)',
};
