import { Policy, Insurer } from '../types';

// Insurers
const starHealth: Insurer = { name: 'Star Health' };
const nivaBupa: Insurer = { name: 'Niva Bupa' };
const careHealth: Insurer = { name: 'Care Health' };
const hdfcErgo: Insurer = { name: 'HDFC Ergo' };
const acko: Insurer = { name: 'Acko' };
const adityaBirla: Insurer = { name: 'Aditya Birla' };
const manipalCigna: Insurer = { name: 'Manipal Cigna' };
const iciciLombard: Insurer = { name: 'ICICI Lombard' };
const bajajAllianz: Insurer = { name: 'Bajaj Allianz' };
const tataAig: Insurer = { name: 'Tata AIG' };

export const insurers: Insurer[] = [starHealth, nivaBupa, careHealth, hdfcErgo, acko, adityaBirla, manipalCigna, iciciLombard, bajajAllianz, tataAig];


// Policies
export const policies: Policy[] = [
  // --- Star Health Policies ---
  {
    id: 'star-comprehensive',
    insurer: starHealth,
    policyName: 'Star Comprehensive Insurance Policy',
    shortUsp: 'All-inclusive plan with in-built accident, maternity, and newborn cover.',
    features: {
      policyType: { text: 'Individual & Family Floater' },
      entryAge: { text: 'Adult: 18-65; Child: 91 days-25 years' },
      sumInsured: { text: '₹5L to ₹1 Crore' },
      premium: { text: 'Indicative for 1A+1C (age 35) for ₹10L SI is ₹15,635/year' },
      hospitalization: { text: 'Up to SI. Room Rent: Private Single A/C Room (Actuals)' },
      prePostHosp: { text: '60 days pre / 90 days post' },
      dayCare: { text: 'All day care procedures are covered' },
      restoreBenefit: { text: '100% of base SI restored once per policy year. Can be used for the same illness.' },
      cumulativeBonus: { text: 'For SI ≥ ₹7.5L: 100% of base SI after one claim-free year. For SI of ₹5L: 50% per year, max 100%.' },
      chronicDisease: { text: 'Covers Psychiatric & Psychosomatic treatment. Optional Buy-back for PED reduces waiting period from 36 to 12 months.' },
      maternity: { text: 'Covered up to ₹1L (Caesarean) / ₹50k (Normal) for SI ≥ ₹50L. Waiting Period: 24 months.' },
      newbornCover: { text: 'Covered up to ₹2L (for SI ≥ ₹50L) from Day 1, including congenital disorders. Vaccinations up to ₹10k.' },
      wellness: { text: 'Star Wellness Program: Earn reward points for up to 10% premium discount. Health Check-up: For every claim-free year.' },
      opdCover: { text: 'Out-patient Dental & Ophthalmic: Covered up to ₹15k after a 3-year block.'},
      otherBenefits: { text: 'In-built Accidental Death & PTD Cover. Bariatric Surgery Cover (standard). Hospital Cash Benefit.' },
      waitingPeriods: { text: 'Initial: 30 days. Specific: 24 months. PED: 36 months (12 with buy-back). Maternity: 24 months.' },
      exclusions: { text: 'Standard exclusions.' },
      usps: { text: 'Truly Comprehensive "battery-included" plan. In-built Personal Accident cover, robust Maternity & Newborn cover. Generous & Fast Cumulative Bonus (100% in one year). Same illness restoration.' },
    },
  },
  {
    id: 'star-young',
    insurer: starHealth,
    policyName: 'Star Young Star Insurance Policy',
    shortUsp: 'Low 12-month waiting period for PEDs and 300% restoration benefit.',
    features: {
      policyType: { text: 'Individual & Family Floater' },
      entryAge: { text: 'Adult: 18-40; Child: 91 days-25 years' },
      sumInsured: { text: '₹5L to ₹1 Crore' },
      premium: { text: 'Lower premiums targeting younger customers.' },
      hospitalization: { text: 'Up to SI. Room Rent: Single Private A/C Room.' },
      prePostHosp: { text: '60 days pre / 90 days post' },
      dayCare: { text: 'All day care procedures covered.' },
      restoreBenefit: { text: 'Star Restore Benefit: 100% of base SI restored up to 3 times per policy year.' },
      cumulativeBonus: { text: '20% of base SI for each claim-free year, max up to 100%.' },
      chronicDisease: { text: 'Covered after standard PED waiting period of 12 months.' },
      maternity: { text: 'Not covered.' },
      newbornCover: { text: 'Not covered.' },
      wellness: { text: 'Star Wellness Program: Earn rewards for premium discounts. Health Check-up for every claim-free year.' },
      opdCover: { text: 'Not Covered' },
      otherBenefits: { text: 'Road Traffic Accident (RTA) Benefit: Additional 25% of SI (max ₹10L).' },
      waitingPeriods: { text: 'Initial: 30 days. Specific Diseases: 12 months. Pre-Existing Diseases (PED): 12 months.' },
      exclusions: { text: 'Standard exclusions.' },
      usps: { text: 'Low Waiting Periods: Only 12 months for PEDs. Star Restore Benefit: Up to 300% restoration. RTA Benefit for young adults. Incentivized Renewal.' },
    },
  },
  {
    id: 'star-fho',
    insurer: starHealth,
    policyName: 'Star Family Health Optima Insurance Plan',
    shortUsp: 'Features 3X automatic restoration and covers Assisted Reproduction Treatment.',
    features: {
      policyType: { text: 'Family Floater' },
      entryAge: { text: 'Adult: 18-65 years; Child: 16 days-25 years' },
      sumInsured: { text: '₹3L, ₹4L, ₹5L, ₹10L, ₹15L, ₹20L, ₹25L' },
      premium: { text: 'Varies based on age of eldest member and family size.' },
      hospitalization: { text: 'Up to SI. Room Rent: Capped at ₹5,000 for SI < ₹10L; Single Private A/C Room for SI ≥ ₹10L.' },
      prePostHosp: { text: '60 days pre / 90 days post' },
      dayCare: { text: 'All day care procedures covered.' },
      restoreBenefit: { text: 'Automatic Restoration: 100% of base SI restored up to 3 times per policy year.' },
      cumulativeBonus: { text: 'No Cumulative Bonus. Instead, offers Health Check-up benefit.' },
      chronicDisease: { text: 'Covered after standard PED waiting period of 36 months.' },
      maternity: { text: 'Includes cover for Assisted Reproduction Treatment up to ₹2L after a 36-month wait.' },
      newbornCover: { text: 'Covered from Day 16 up to 10% of SI (max ₹50,000), subject to mother being insured for 12 months.' },
      wellness: { text: 'Health Check-up benefit instead of cumulative bonus.' },
      opdCover: { text: 'Not Covered' },
      otherBenefits: { text: 'Assisted Reproduction Treatment. Organ Donor Expenses. Domiciliary Hospitalization. Covers more than 400 day care procedures.' },
      waitingPeriods: { text: 'Initial: 30 days. Specific Diseases: 24 months. PED: 36 months.' },
      exclusions: { text: 'Standard exclusions.' },
      usps: { text: '3X Automatic Restoration. Assisted Reproduction Treatment Cover (a rare benefit). Newborn Cover included as a standard feature.' },
    },
  },
   {
    id: 'star-women-care',
    insurer: starHealth,
    policyName: 'Star Women Care Insurance Policy',
    shortUsp: 'Holistic women-centric plan with short 12-month maternity wait period.',
    features: {
      policyType: { text: 'Individual & Family Floater (must include one female)' },
      entryAge: { text: 'Adult Female: 18 to 75 years' },
      sumInsured: { text: '₹5L to ₹1 Crore' },
      premium: { text: 'Varies' },
      hospitalization: { text: 'Standard hospitalization benefits up to SI.' },
      prePostHosp: { text: 'Standard' },
      dayCare: { text: 'All day care procedures covered.' },
      restoreBenefit: { text: 'Unlimited Automatic Restoration of 100% of SI.' },
      cumulativeBonus: { text: 'Not specified as a distinct benefit.' },
      chronicDisease: { text: 'Lump Sum Cancer Benefit for women: 50% of SI paid on diagnosis of specified cancers.' },
      maternity: { text: 'Ante-Natal Care (after 24m wait). Delivery Expenses: Covered up to limits (e.g., ₹1L for Caesarean for 1Cr SI) after a 12-month wait (if SI ≥ ₹10L).' },
      newbornCover: { text: 'Covered from Day 1, including congenital defects, up to 25% of SI (max ₹10L). Includes vaccinations.' },
      wellness: { text: 'Not explicitly mentioned, but focus is on holistic health.' },
      opdCover: { text: 'Covered only for women based on SI amount' },
      otherBenefits: { text: 'In Utero Fetal Surgery. Assisted Reproduction Treatment. Star Mother Cover (covers hospitalization of the mother of an insured child <12 years).' },
      waitingPeriods: { text: 'Delivery: 12/24 months. Specific Diseases: 24 months. PED: 24 months. Cancer Cover: 12 months.' },
      exclusions: { text: 'Standard exclusions apply.' },
      usps: { text: 'Holistic Women-centric Coverage. Short Maternity Waiting Period (12 months for delivery). Comprehensive Newborn Cover. Lump Sum Cancer Benefit. In Utero Fetal Surgery cover.' },
    },
  },
  {
    id: 'star-senior-citizen',
    insurer: starHealth,
    policyName: 'Senior Citizens Red Carpet Policy',
    shortUsp: 'No pre-insurance medical screening and 12-month waiting for PEDs.',
    features: {
      policyType: { text: 'Individual & Family Floater' },
      entryAge: { text: '60 to 75 years' },
      sumInsured: { text: '₹1L to ₹25L' },
      premium: { text: 'Varies.' },
      hospitalization: { text: 'Covered, but with 30% co-payment on all admissible claims.' },
      prePostHosp: { text: '30 days pre / 60 days post' },
      dayCare: { text: 'All day care procedures covered.' },
      restoreBenefit: { text: 'Not specified.' },
      cumulativeBonus: { text: 'Not specified.' },
      chronicDisease: { text: 'Pre-Existing Diseases covered from the 13th month onwards.' },
      maternity: { text: 'Not applicable.' },
      newbornCover: { text: 'Not applicable.' },
      wellness: { text: 'Not specified.' },
      opdCover: { text: 'Out-patient Consultations: Covered up to specified limits (e.g., ₹200 per consultation).' },
      otherBenefits: { text: 'Fixed Co-payment structure.' },
      waitingPeriods: { text: 'Initial: 30 days. Specific Diseases: 24 months. PED: 12 months.' },
      exclusions: { text: 'Standard exclusions.' },
      usps: { text: 'No Pre-insurance Medical Screening Required. Short 12-month Waiting Period for PEDs. OPD Consultation benefits.' },
    },
  },
  {
    id: 'star-arogya-sanjeevani',
    insurer: starHealth,
    policyName: 'Arogya Sanjeevani Policy',
    shortUsp: 'Standardized, affordable plan mandated by IRDAI.',
    features: {
      policyType: { text: 'Individual & Family Floater' },
      entryAge: { text: 'Adult: 18-65 years; Child: 3 months-25 years' },
      sumInsured: { text: '₹50,000 to ₹10 Lakh' },
      premium: { text: 'Varies' },
      hospitalization: { text: 'Covered, with sub-limits. Room Rent: Up to 2% of SI (max ₹5,000/day). ICU: Up to 5% of SI (max ₹10,000/day). 5% co-payment on all claims.' },
      prePostHosp: { text: '30 days pre / 60 days post' },
      dayCare: { text: 'All day care procedures covered.' },
      restoreBenefit: { text: 'Not available.' },
      cumulativeBonus: { text: '5% of SI for each claim-free year, max up to 50%.' },
      chronicDisease: { text: 'Covered after PED waiting period of 48 months.' },
      maternity: { text: 'Not applicable.' },
      newbornCover: { text: 'Not applicable.' },
      wellness: { text: 'Not applicable.' },
      opdCover: { text: 'Not Covered' },
      otherBenefits: { text: 'Cataract Treatment (up to 25% of SI), AYUSH Treatment, Road Ambulance (max ₹2,000).' },
      waitingPeriods: { text: 'Initial: 30 days. Specific Diseases: 24 months. PED: 48 months.' },
      exclusions: { text: 'Standardized as per IRDAI guidelines.' },
      usps: { text: 'Affordability: Low-cost, entry-level product. Standardization: Uniform features across all insurers. Simplicity: Easy-to-understand basic coverage.' },
    },
  },
  {
    id: 'star-cancer-care',
    insurer: starHealth,
    policyName: 'Star Cancer Care Platinum',
    shortUsp: 'Specialized plan for cancer patients/survivors (Stage 1/2 diagnosis).',
    features: {
      policyType: { text: 'Individual, Benefit-based' },
      entryAge: { text: '5 months to 65 years (For those already diagnosed with Cancer Stage 1 or 2)' },
      sumInsured: { text: '₹5L, ₹7.5L, ₹10L' },
      premium: { text: 'Varies' },
      hospitalization: { text: 'Indemnity Cover: Up to 50% of SI for hospitalization expenses related to cancer treatment.' },
      prePostHosp: { text: 'Not applicable (Benefit-based).' },
      dayCare: { text: 'Covered under indemnity part.' },
      restoreBenefit: { text: 'Not applicable.' },
      cumulativeBonus: { text: 'Not applicable.' },
      chronicDisease: { text: 'Specifically for cancer patients/survivors.' },
      maternity: { text: 'Not applicable.' },
      newbornCover: { text: 'Not applicable.' },
      wellness: { text: 'Not applicable.' },
      opdCover: { text: 'Covered under indemnity part.' },
      otherBenefits: { text: 'Lump Sum Payout: 50% of SI on first diagnosis of recurrence/metastasis. Surgical Oncology: Covered up to 100% of SI. Covers Co-morbidities.' },
      waitingPeriods: { text: 'Initial waiting period of 30 days. Specific waiting period of 12 months.' },
      exclusions: { text: 'Does not cover cancer diagnosed at Stage 3 or 4.' },
      usps: { text: 'Specifically for Cancer Patients/Survivors (Stage 1/2). Hybrid Payout: Combines lump-sum with indemnity. Covers Co-morbidities.' },
    },
  },
  {
    id: 'star-accident-care',
    insurer: starHealth,
    policyName: 'Star Accident Care Individual Policy',
    shortUsp: 'High sum insured up to ₹7 Crore and comprehensive disability cover.',
    features: {
      policyType: { text: 'Individual, Fixed Benefit' },
      entryAge: { text: 'Adult: 18 to 70 Years; Dependant children: 5 months to 25 years' },
      sumInsured: { text: '₹1L to ₹7 Crore' },
      premium: { text: 'Varies' },
      hospitalization: { text: 'Hospitalization expenses due to accident (optional).' },
      prePostHosp: { text: 'Not applicable.' },
      dayCare: { text: 'Not applicable.' },
      restoreBenefit: { text: 'Not applicable.' },
      cumulativeBonus: { text: 'Offers cumulative bonus.' },
      chronicDisease: { text: 'Not applicable.' },
      maternity: { text: 'Not applicable.' },
      newbornCover: { text: 'Not applicable.' },
      wellness: { text: 'Not applicable.' },
      opdCover: { text: 'Not applicable.' },
      otherBenefits: { text: 'Accidental Death: 100% of SI. Permanent Total Disablement: Up to 150% of SI. Temporary Total Disablement: Weekly payout of 1% of SI. Education Grant.' },
      waitingPeriods: { text: 'Not applicable for accident policies.' },
      exclusions: { text: 'Self-inflicted injury, suicide, influence of drugs/alcohol, war, hazardous sports.' },
      usps: { text: 'High Sum Insured options. Comprehensive Disability Cover (permanent, temporary, total, partial). Enhanced Benefits (education grant, cumulative bonus).' },
    },
  },
  {
    id: 'star-assure',
    insurer: starHealth,
    policyName: 'Star Assure Insurance Policy',
    shortUsp: 'Guaranteed issuance with no medical screening required.',
    features: {
      policyType: { text: 'Individual, Fixed Benefit' },
      entryAge: { text: 'Individual : Min 18 Years to Max 75 Years, Dependent Children: Min 91 Days to Max17Years\nFloater : Min 18 Years to Max 75 Years, Dependent Children: Min 16 Days to Max17 Years Entry age is 18 - 75 years,' },
      sumInsured: { text: '₹5L to 2 Crore' },
      premium: { text: 'Affordable premium' },
      hospitalization: { text: 'Not applicable (fixed benefit)' },
      prePostHosp: { text: 'Not applicable.' },
      dayCare: { text: 'Not applicable.' },
      restoreBenefit: { text: 'Not applicable.' },
      cumulativeBonus: { text: 'Not specified.' },
      chronicDisease: { text: 'Lump Sum Payout: 100% of SI on first diagnosis of covered Critical Illnesses.' },
      maternity: { text: 'Not applicable.' },
      newbornCover: { text: 'Not applicable.' },
      wellness: { text: 'Premium discount on renewal for maintaining good health.' },
      opdCover: { text: 'Non-Medical Expenses: A lump sum of ₹10,000 is paid.' },
      otherBenefits: { text: 'Accidental Death/PTD: An amount equal to the SI is paid in case of Accidental Death or Permanent Total Disablement (PTD).' },
      waitingPeriods: { text: '90 days for Critical Illness diagnosis. Any illness diagnosed within the 90-day waiting period is excluded.' },
      exclusions: { text: 'Any pre-existing illness.' },
      usps: { text: 'Guaranteed Issuance: No pre-acceptance medical screening required. Dual Benefit: Combines Critical Illness and Personal Accident cover. Simple, Fixed Payout.' },
    },
  },

  // --- Competitor Policies ---
  {
    id: 'care-supreme',
    insurer: careHealth,
    policyName: 'Care Supreme',
    shortUsp: 'Unlimited automatic recharge and bonus up to 500% with add-on.',
    features: {
      policyType: { text: 'Individual & Family Floater' },
      entryAge: { text: 'Adult: 18-99; Child: 90 days-24 years' },
      sumInsured: { text: '₹5L, ₹7L, ₹10L, ₹15L, ₹25L, ₹50L, ₹1 Crore' },
      premium: { text: 'Starting from ₹372/month for a ₹5L cover (indicative)' },
      hospitalization: { text: 'In-patient care, room rent, ICU charges covered up to SI' },
      prePostHosp: { text: '60 days pre / 180 days post' },
      dayCare: { text: 'All day care procedures covered' },
      restoreBenefit: { text: 'Unlimited Automatic Recharge up to SI for same or unrelated illness' },
      cumulativeBonus: { text: '50% of SI per year, max 100%. No reduction on claim. Optional Add-on "Cumulative Bonus Super" boosts SI up to 500%.' },
      chronicDisease: { text: 'Instant Cover (Add-on): Covers Diabetes, Hypertension, Hyperlipidemia, Asthma from Day 31.' },
      maternity: { text: 'Not covered in this plan.' },
      newbornCover: { text: 'Not covered.' },
      wellness: { text: 'Wellness Benefit (Add-on): Up to 30% discount. Be-fit (Add-on): Unlimited access to fitness centers. Unlimited e-consultations.' },
      opdCover: {text: 'Unlimited e-consultations with General Physicians.'},
      otherBenefits: { text: 'Claim Shield (Add-on): Covers non-payable items like gloves, masks. AYUSH treatment, Domiciliary Hospitalization.' },
      waitingPeriods: { text: 'Initial: 30 days. Named Ailments: 24 months. PED: 36 months (can be reduced with add-on).' },
      exclusions: { text: 'Self-inflicted injuries, adventure sports, war, cosmetic surgery.' },
      usps: { text: 'Cumulative Bonus Super (Add-on). Instant Cover (Add-on) for lifestyle diseases. Claim Shield (Add-on). Unlimited Automatic Recharge for any illness.' },
    },
  },
    {
    id: 'care-advantage',
    insurer: careHealth,
    policyName: 'Care Advantage',
    shortUsp: 'High sum insured up to ₹6 Cr and optional global coverage.',
    features: {
      policyType: { text: 'Individual & Family Floater' },
      entryAge: { text: 'Adult: 5+ years; Child: 91 days-24 years' },
      sumInsured: { text: '₹25L, ₹50L, ₹1Cr, ₹2Cr, ₹3Cr, ₹6Cr' },
      premium: { text: 'Starting from ₹1305/month for a ₹1 Crore cover (indicative)' },
      hospitalization: { text: 'In-patient care, No sub-limit on Room Rent or ICU charges' },
      prePostHosp: { text: '60 days pre / 180 days post' },
      dayCare: { text: '540+ listed day care procedures covered' },
      restoreBenefit: { text: 'Automatic Recharge up to SI (Once per policy year). Optional unlimited recharge.' },
      cumulativeBonus: { text: 'No Claim Bonus: 10% of SI per claim-free year, max up to 50%. Reduced by 10% on claim. Optional NCB Super add-on.' },
      chronicDisease: { text: 'Covered after PED waiting period of 48 months. Option to reduce wait period via add-on.' },
      maternity: { text: 'Not covered in the base plan.' },
      newbornCover: { text: 'Not covered.' },
      wellness: { text: 'Unlimited e-consultations with General Physicians.' },
      opdCover: { text: 'Unlimited e-consultations as a standard benefit.' },
      otherBenefits: { text: 'Global Coverage (Add-on): Optional "Protect Plus" for worldwide medical coverage. Organ Donor Expenses, AYUSH treatment.' },
      waitingPeriods: { text: 'Initial: 30 days. Named Ailments: 24 months. PED: 48 months (can be reduced).' },
      exclusions: { text: 'Self-inflicted injury, alcohol/drug abuse, congenital external diseases.' },
      usps: { text: 'High Sum Insured Options up to ₹6 Crore. Optional Global Coverage. Unlimited E-consultations as a standard benefit.' },
    },
  },
  {
    id: 'niva-reassure',
    insurer: nivaBupa,
    policyName: 'ReAssure 2.0',
    shortUsp: 'Unlimited restoration for life and premium lock at entry age.',
    features: {
      policyType: { text: 'Individual & Family Floater' },
      entryAge: { text: 'Adult: 18-65; Child: 91 days-30 years' },
      sumInsured: { text: '₹5L to ₹1 Crore' },
      premium: { text: 'Starts from ₹7,326/year for a ₹5L cover' },
      hospitalization: { text: 'In-patient care up to SI. No room rent capping (all room types, including suites in some variants).' },
      prePostHosp: { text: '60 days pre / 180 days post' },
      dayCare: { text: 'All day care procedures covered.' },
      restoreBenefit: { text: 'ReAssure "Forever": Unlimited reinstatement of base SI, for life, triggered by the first claim. For same or different illness.' },
      cumulativeBonus: { text: 'Booster+: Unused base SI is carried forward to the next year. Max accumulation up to 10X of base SI.' },
      chronicDisease: { text: 'Disease Management (Add-on): Day 1 coverage for Diabetes and Hypertension.' },
      maternity: { text: 'Not available in this plan.' },
      newbornCover: { text: 'Not available.' },
      wellness: { text: 'Live Healthy: Up to 30% discount on renewal premium based on step count. Annual Health Check-up: From Day 1, for all members.' },
      opdCover: { text: 'Unlimited e-consultations.' },
      otherBenefits: { text: 'Lock the Clock: Premium is locked at entry age until first claim. Safeguard+ (Add-on): Covers non-payable items.' },
      waitingPeriods: { text: 'Initial: 30 days. Specified Diseases: 24 months. PED: 24 months.' },
      exclusions: { text: 'Cosmetic surgery, self-inflicted injuries, adventure sports.' },
      usps: { text: 'ReAssure "Forever" (unlimited restoration for life). Lock the Clock (premium freeze). Booster+ (carry forward SI up to 10X). Safeguard+ (Add-on for non-payables).' },
    },
  },
  {
    id: 'niva-premia',
    insurer: nivaBupa,
    policyName: 'Health Premia',
    shortUsp: 'High maternity limits (up to ₹2L) and in-built international coverage.',
    features: {
        policyType: { text: 'Individual & Family Floater' },
        entryAge: { text: 'Not explicitly stated' },
        sumInsured: { text: 'Gold Plan: ₹10L-₹50L; Platinum Plan: ₹1Cr-₹3Cr' },
        premium: { text: 'Indicative for ₹1 Crore floater is ₹89,005/year' },
        hospitalization: { text: 'In-patient care up to SI. No room rent capping (all covered in Platinum).' },
        prePostHosp: { text: '90 days pre / 180 days post' },
        dayCare: { text: 'All day care treatments covered' },
        restoreBenefit: { text: 'Refill Benefit: 100% of base SI restored once per policy year for any illness.' },
        cumulativeBonus: { text: 'Loyalty Additions: 10% of base SI added each year, max up to 100%. Optional enhanced loyalty up to 200%.' },
        chronicDisease: { text: 'Covered after standard PED waiting period of 24 months.' },
        maternity: { text: 'Worldwide Maternity Cover: Up to ₹2L (Platinum). Covers newborn from Day 1. Waiting period 24 months.' },
        newbornCover: { text: 'Included in maternity cover, from Day 1.' },
        wellness: { text: 'Annual Health Check-up: From Day 1, with high limits (e.g., up to ₹10,000 per person in Platinum). Access to Health Coach.' },
        opdCover: { text: 'OPD Cover: Up to ₹50,000 in Platinum plan.' },
        otherBenefits: { text: 'International Coverage: For planned and emergency treatments worldwide. In-built Travel Insurance. Premium Waiver benefit.' },
        waitingPeriods: { text: 'Initial: 30 days. Specified Diseases: 12 months. PED: 24 months. Maternity: 24 months.' },
        exclusions: { text: 'Cosmetic surgery, unproven treatments, hazardous sports.' },
        usps: { text: 'Comprehensive Global Coverage. High Maternity Limits. In-built Multi-trip Travel Insurance. High-value OPD and Health Check-up.' },
    }
  },
  {
    id: 'hdfc-optima-secure',
    insurer: hdfcErgo,
    policyName: 'Optima Secure',
    shortUsp: '4X coverage promise and in-built cover for non-medical items.',
    features: {
      policyType: { text: 'Individual & Family Floater' },
      entryAge: { text: 'Adult: 18+; Child: 91 days-25 years' },
      sumInsured: { text: '₹5L to ₹2 Crore' },
      premium: { text: 'Varies by age, SI, location. No-cost installment options available.' },
      hospitalization: { text: 'In-patient care up to SI. No room rent capping.' },
      prePostHosp: { text: '60 days pre / 180 days post' },
      dayCare: { text: 'All day care treatments covered.' },
      restoreBenefit: { text: 'Automatic Restore Benefit: 100% restoration. Can be unlimited times if opted.' },
      cumulativeBonus: { text: 'Plus Benefit: 100% additional SI over 2 renewals (50% each year). Part of 4X Coverage promise.' },
      chronicDisease: { text: 'Covered after 36 months. Optional add-on for Day 31 coverage.' },
      maternity: { text: 'Available as part of the "Parenthood" add-on cover.' },
      newbornCover: { text: 'Part of "Parenthood" add-on.' },
      wellness: { text: 'Preventive Health Check-up: Available every policy year after the first year.' },
      opdCover: {text: 'Not a core feature.'},
      otherBenefits: { text: 'Secure Benefit: 100% additional SI from Day 1. Protect Benefit: In-built cover for non-medical consumables. Global Cover (optional).' },
      waitingPeriods: { text: 'Initial: 30 days. Specific Diseases: 24 months. PED: 36 months (can be modified with add-on).' },
      exclusions: { text: 'Adventure sports, self-inflicted injuries, war, etc.' },
      usps: { text: '4X Coverage Promise (simple value multiplication). Secure Benefit (instantly doubles cover). Protect Benefit (in-built non-medical expenses cover). No-Cost Installment options.' },
    },
  },
  {
    id: 'hdfc-optima-restore',
    insurer: hdfcErgo,
    policyName: 'my:Optima Restore',
    shortUsp: '100% restoration & doubles coverage in 2 claim-free years.',
    features: {
      policyType: { text: 'Individual & Family Floater' },
      entryAge: { text: 'Adult: up to 65; Child: 91 days-25 years' },
      sumInsured: { text: '₹3L, ₹5L, ₹10L, ₹15L, ₹20L, ₹25L, ₹50L' },
      premium: { text: 'Varies by age, SI, and location.' },
      hospitalization: { text: 'In-patient care up to SI. No sub-limit on room rent.' },
      prePostHosp: { text: '60 days pre / 180 days post' },
      dayCare: { text: 'All day care procedures covered.' },
      restoreBenefit: { text: '100% Restore Benefit: Instantly restores 100% of base SI upon partial or complete utilization, once per policy year.' },
      cumulativeBonus: { text: '2X Multiplier Benefit: 50% increase in base SI for each claim-free year, up to a maximum of 100%.' },
      chronicDisease: { text: 'Covered after standard PED waiting period of 36 months.' },
      maternity: { text: 'Not covered in this plan.' },
      newbornCover: { text: 'Not covered.' },
      wellness: { text: 'Preventive Health Check-up: Available at renewal, with limits based on SI.' },
      opdCover: { text: 'E-Opinion for critical illness.' },
      otherBenefits: { text: 'Organ Donor, Domiciliary Treatment up to SI. Daily Cash for shared accommodation.' },
      waitingPeriods: { text: 'Initial: 30 days. Specific Diseases: 24 months. PED: 36 months.' },
      exclusions: { text: 'Abuse of intoxicants, pregnancy, dental treatment, cosmetic surgery.' },
      usps: { text: '100% Restore Benefit (strong and simple-to-understand). 2X Multiplier Benefit (quick way to double coverage).' },
    },
  },
  {
    id: 'acko-platinum',
    insurer: acko,
    policyName: 'ACKO Platinum Health Policy',
    shortUsp: '100% bill payment, zero deductions, and optional zero waiting period.',
    features: {
      policyType: { text: 'Individual & Family Floater' },
      entryAge: { text: 'Adult: 18+; Child: 91 days onwards' },
      sumInsured: { text: '₹1 Crore and Unlimited options available' },
      premium: { text: 'Starts at ₹21/day (indicative). Customized based on health conditions.' },
      hospitalization: { text: '100% Hospital Bill Payment: Covers all medical expenses from "syringes to surgeries," including consumables. No Room Rent/ICU limit.' },
      prePostHosp: { text: '60 days pre / 120 days post' },
      dayCare: { text: 'All day care treatments covered.' },
      restoreBenefit: { text: 'Unlimited Restoration: Sum Insured is restored an unlimited number of times for subsequent claims.' },
      cumulativeBonus: { text: 'Inflation Protection: Sum Insured increases by 10% every year, irrespective of claims.' },
      chronicDisease: { text: 'Covered from Day 1 if the Zero Waiting Period option is selected.' },
      maternity: { text: 'Not covered. Treatment for ectopic pregnancy due to accident is covered.' },
      newbornCover: { text: 'Not covered.' },
      wellness: { text: 'Free unlimited teleconsultations with doctors/specialists. Free yearly health check-ups for all members.' },
      opdCover: { text: 'Free unlimited teleconsultations.' },
      otherBenefits: { text: 'Accident-related dental and vision care covered. Domestic Evacuation covered up to SI.' },
      waitingPeriods: { text: 'Zero Waiting Period option available, which eliminates all waiting periods (Initial, Specific Disease, PED) from Day 1.' },
      exclusions: { text: 'Maternity expenses, non-accident related dental/vision care.' },
      usps: { text: '100% Hospital Bill Payment / Zero Deductions. Zero Waiting Period Option. Unlimited Sum Insured option. Unlimited Restorations. Inflation-linked NCB.' },
    },
  },
   {
    id: 'acko-arogya-sanjeevani',
    insurer: acko,
    policyName: 'Arogya Sanjeevani Policy',
    shortUsp: 'Affordable, standardized plan with flexible payment options.',
    features: {
      policyType: { text: 'Individual & Family Floater' },
      entryAge: { text: 'Adult: 18-65 years; Child: 3 months-25 years' },
      sumInsured: { text: '₹50,000 to ₹10 Lakh' },
      premium: { text: 'Varies. Monthly, quarterly, half-yearly, and annual payment options available.' },
      hospitalization: { text: 'Covered, but with sub-limits. Room Rent: Up to 2% of SI (max ₹5,000/day). ICU: Up to 5% of SI (max ₹10,000/day).' },
      prePostHosp: { text: '30 days pre / 60 days post' },
      dayCare: { text: 'All day care procedures covered.' },
      restoreBenefit: { text: 'Not available in the standard plan.' },
      cumulativeBonus: { text: '5% of SI for each claim-free year, max up to 50%.' },
      chronicDisease: { text: 'Covered after the standard 48-month PED waiting period.' },
      maternity: { text: 'Not covered.' },
      newbornCover: { text: 'Not a standard feature.' },
      wellness: { text: 'Not a standard feature.' },
      otherBenefits: { text: 'AYUSH Treatment, Cataract Treatment (up to 25% of SI, max ₹40,000), Road Ambulance (max ₹2,000).' },
      waitingPeriods: { text: 'Initial: 30 days. Specific Diseases: 24 months. PED: 48 months.' },
      exclusions: { text: 'Standard exclusions like self-inflicted injuries, cosmetic surgery, obesity treatment.' },
      usps: { text: 'Affordability, Standardization, Simplicity.' },
    },
  },
  {
    id: 'aditya-birla-platinum',
    insurer: adityaBirla,
    policyName: 'Activ Health Platinum (Enhanced Variant)',
    shortUsp: 'Earn up to 100% of premium back and Day 1 cover for chronic conditions.',
    features: {
      policyType: { text: 'Individual & Family Floater' },
      entryAge: { text: 'Adult: 18+ (No max age); Child: 91 days-25 years' },
      sumInsured: { text: '₹2L to ₹2 Crore' },
      premium: { text: 'Indicative for 60-year-old male with high cholesterol is ₹17,944/year (excl. GST) for a ₹5L cover' },
      hospitalization: { text: 'In-patient hospitalization (including for mental illness) covered up to SI. Room choice depends on SI (Any Room for SI > ₹7L)' },
      prePostHosp: { text: '60 days pre / 180 days post' },
      dayCare: { text: '586 day-care procedures covered' },
      restoreBenefit: { text: 'Reload of Sum Insured: 100% of SI reloaded once per year for an unrelated illness.' },
      cumulativeBonus: { text: '50% of SI increase per claim-free year, max up to 100% of SI (up to ₹1 Cr).' },
      chronicDisease: { text: 'Chronic Management Program: Day 1 cover for Asthma, High Blood Pressure, High Cholesterol, Diabetes. Includes expert health coaching.' },
      maternity: { text: 'Available as an optional cover.' },
      newbornCover: { text: 'Part of optional maternity cover.' },
      wellness: { text: 'HealthReturns™: Earn up to 100% of premium back as rewards for completing "Active Dayz™". Rewards can be used to pay premiums or other health expenses.' },
      opdCover: {text: 'Second E-opinion for major illnesses.'},
      otherBenefits: { text: 'Expert Health Coaching for medical, nutritional, and mental wellness. AYUSH, Obesity Treatment, Cashless Home Treatment.' },
      waitingPeriods: { text: 'Initial: 30 days. Listed Diseases: 24 months. PED: 36 months.' },
      exclusions: { text: 'Intentional self-injury, cosmetic surgery, abuse of intoxicants.' },
      usps: { text: 'HealthReturns™ (up to 100% premium back). Chronic Management Program (Day 1 coverage). High No Claim Bonus (doubles cover in 2 years). Expert Health Coaching.' },
    },
  },
  {
    id: 'manipal-prohealth-prime',
    insurer: manipalCigna,
    policyName: 'ProHealth Prime (Advantage Variant)',
    shortUsp: 'Cashless OPD cover up to ₹50,000/year and unlimited restoration.',
    features: {
      policyType: { text: 'Individual & Family Floater' },
      entryAge: { text: 'Adult: 18+; Child: 91 days-25 years' },
      sumInsured: { text: 'Advantage: ₹5L to ₹1 Crore' },
      premium: { text: 'Indicative for Advantage plan with ₹5L SI is ₹14,915/year' },
      hospitalization: { text: 'In-patient care up to SI. Option for "Any Room" category.' },
      prePostHosp: { text: '60 days pre / 180 days post' },
      dayCare: { text: 'All day care procedures covered up to SI.' },
      restoreBenefit: { text: 'Unlimited Restoration: 100% of SI restored unlimited times for related or unrelated illnesses (from 2nd claim onwards).' },
      cumulativeBonus: { text: 'Guaranteed Bonus: 25% of base SI per policy year, max up to 200%. Optional 50% "Booster" available.' },
      chronicDisease: { text: 'Covers Mental Illness, HIV/AIDS, STDs up to SI.' },
      maternity: { text: 'Enhance Package (Optional): Covers maternity, newborn expenses, and 1st-year vaccinations up to 10% of SI (max ₹1L).' },
      newbornCover: { text: 'Part of optional Enhance Package.' },
      wellness: { text: 'Wellness Program: Earn rewards up to 20% of base premium. Annual Health Check-up from year 1.' },
      opdCover: { text: 'Advantage Plan Only: Cashless OPD cover up to ₹50,000/year for consultations, diagnostics, and pharmacy.' },
      otherBenefits: { text: 'Switch Off Benefit: Premium discount when traveling abroad. Premium Waiver. Non-Medical Expenses Cover (Optional).' },
      waitingPeriods: { text: 'Initial: 30 days. PED: 24 months (for SI ≥ ₹7.5L), 36 months (for SI < ₹7.5L). Maternity: 36 months.' },
      exclusions: { text: 'Standard exclusions apply.' },
      usps: { text: 'Cashless OPD Cover (Advantage Plan). Unlimited Restoration for related illnesses. Guaranteed Cumulative Bonus. Switch Off Benefit. Highly Customizable.' },
    },
  },
  {
    id: 'tata-medicare-premier',
    insurer: tataAig,
    policyName: 'MediCare Premier',
    shortUsp: 'In-built consumables cover and OPD for dental & diagnostics.',
    features: {
        policyType: { text: 'Individual & Family Floater' },
        entryAge: { text: 'Adult: 18-65; Child: 91 days-25 years' },
        sumInsured: { text: '₹5L to ₹3 Crore' },
        premium: { text: 'Varies by age, SI, and zone.' },
        hospitalization: { text: 'In-patient care up to SI. No room rent restrictions.' },
        prePostHosp: { text: '60 days pre / 90 days post' },
        dayCare: { text: 'All day-care treatments covered' },
        restoreBenefit: { text: '100% of base SI restored once per policy year. Can be used for unrelated illness, or related illness after 45 days.' },
        cumulativeBonus: { text: '50% of base SI for each claim-free year, max up to 100%. Reduced by 50% on claim.' },
        chronicDisease: { text: 'Covered after standard PED waiting period of 36 months.' },
        maternity: { text: 'Up to ₹50,000 (₹60,000 for a girl child) after a 48-month waiting period.' },
        newbornCover: { text: 'Covered up to ₹10,000. Vaccination cover up to ₹10,000 (₹15,000 for girl child).' },
        wellness: { text: 'Wellness Services: Includes unlimited teleconsultations. Wellness Program: Earn rewards via fitness activities. Annual Health Check-up.' },
        opdCover: { text: 'OPD Dental Treatment: Up to ₹10,000 after 2 years. High-End Diagnostics (OPD): Up to ₹25,000/year.' },
        otherBenefits: { text: 'Global Cover: For planned hospitalization abroad. Consumables Benefit: In-built cover for non-medical items. Bariatric Surgery Cover up to SI.' },
        waitingPeriods: { text: 'Initial: 30 days. Specific Diseases: 24 months. PED: 24 months. Maternity: 48 months.' },
        exclusions: { text: 'Congenital external diseases, alcoholic pancreatitis.' },
        usps: { text: 'Global Cover for planned treatments. In-built Consumables Benefit. Generous Cumulative Bonus (50% per year). OPD coverage for dental and high-end diagnostics. Backed by the TATA brand trust.' },
    }
  },
  {
    id: 'icici-lombard-health-advantedge',
    insurer: iciciLombard,
    policyName: 'Health AdvantEdge',
    shortUsp: 'In-built worldwide cover for high SI and short 24-month PED wait.',
    features: {
        policyType: { text: 'Individual & Family Floater' },
        entryAge: { text: 'Adult: 18-65; Child: 91 days-25 years' },
        sumInsured: { text: '₹5L to ₹3 Crore' },
        premium: { text: 'Indicative for 25-year-old for ₹5L SI is ₹7,786/year' },
        hospitalization: { text: 'Private Single A/C Room' },
        prePostHosp: { text: '60 days pre / 180 days post' },
        dayCare: { text: 'All day care procedures covered' },
        restoreBenefit: { text: '100% of base SI restored for any illness, including for the same person.' },
        cumulativeBonus: { text: 'Guaranteed Bonus: 20% of SI for each claim-free year, max up to 100%' },
        chronicDisease: { text: 'Covered after the PED waiting period of 24 months.' },
        maternity: { text: 'Available as an optional cover with limits up to 10% of base SI (max ₹10L).' },
        newbornCover: { text: 'Part of optional maternity cover.' },
        wellness: { text: 'Wellness and Value Added Services (Optional): Includes teleconsultations, pharmacy/diagnostic services, etc. Annual Health Check-up from year 1.' },
        opdCover: { text: 'Part of optional wellness services.' },
        otherBenefits: { text: 'Worldwide Cover: In-built for SI ≥ ₹25L. Bariatric Surgery Cover. Claim Protector (Optional): Covers non-medical consumables. Convalescence Benefit.' },
        waitingPeriods: { text: 'Initial: 30 days. Specific Diseases: 24 months. PED: 24 months. Bariatric Surgery: 36 months.' },
        exclusions: { text: 'Standard exclusions apply.' },
        usps: { text: 'Very High Sum Insured up to ₹3 Crore. In-built Worldwide Cover for higher SI plans. Short PED Waiting Period of 24 months. Guaranteed Cumulative Bonus of 20%.' },
    },
  },
  {
    id: 'bajaj-allianz-health-guard-gold',
    insurer: bajajAllianz,
    policyName: 'Health Guard (Gold)',
    shortUsp: 'Well-rounded family plan with maternity and newborn cover included.',
    features: {
        policyType: { text: 'Individual & Family Floater' },
        entryAge: { text: 'Adult: 18-65; Child: 3 months-30 years' },
        sumInsured: { text: '₹3L to ₹50L' },
        premium: { text: 'Indicative for 2 Adults (Gold, ₹10L SI) is ₹13,200/year' },
        hospitalization: { text: 'Single Private A/C Room for SI ₹3L-₹7.5L; Any Room for SI ≥ ₹10L.' },
        prePostHosp: { text: '60 days pre / 90 days post' },
        dayCare: { text: '399 day care procedures covered' },
        restoreBenefit: { text: 'Sum Insured Reinstatement: 100% of base SI restored once per year for unrelated illness.' },
        cumulativeBonus: { text: '10% per claim-free year, max 100%.' },
        chronicDisease: { text: 'Covered after standard PED waiting period of 36 months.' },
        maternity: { text: 'Covered after a 72-month (6-year) waiting period. Limits up to ₹25,000 for Caesarean.' },
        newbornCover: { text: 'Covered up to 90 days from birth.' },
        wellness: { text: 'Preventive Health Check-up: Every 3 years. Wellness Discount: Up to 12.5% on renewal.' },
        opdCover: { text: 'Not a primary feature.' },
        otherBenefits: { text: 'AYUSH Hospitalization (up to ₹20,000), Organ Donor Expenses, Bariatric Surgery Cover, Convalescence Benefit.' },
        waitingPeriods: { text: 'Initial: 30 days. Specific Diseases: 24 months. PED: 36 months. Maternity: 72 months.' },
        exclusions: { text: 'Dental treatment, substance abuse, HIV/AIDS, cosmetic surgery.' },
        usps: { text: 'Clear Plan Segmentation (Silver/Gold/Platinum). Maternity and Newborn Cover included. Bariatric Surgery Cover included.' },
    },
  },
  {
    id: 'bajaj-allianz-health-guard-platinum',
    insurer: bajajAllianz,
    policyName: 'Health Guard (Platinum)',
    shortUsp: 'Super NCB up to 150% and additional recharge benefit.',
    features: {
        policyType: { text: 'Individual & Family Floater' },
        entryAge: { text: 'Adult: 18-65; Child: 3 months-30 years' },
        sumInsured: { text: '₹5L to ₹1 Crore' },
        premium: { text: 'Varies by plan, age, SI, and location.' },
        hospitalization: { text: 'Any Room category.' },
        prePostHosp: { text: '60 days pre / 90 days post' },
        dayCare: { text: '399 day care procedures covered' },
        restoreBenefit: { text: 'Sum Insured Reinstatement: 100% of base SI restored once per year for unrelated illness. Plus Recharge Benefit: Additional 20% of SI (max ₹5L) if SI is exhausted.' },
        cumulativeBonus: { text: 'Super NCB: 50% for first 2 years, then 10%, max 150%.' },
        chronicDisease: { text: 'Covered after standard PED waiting period of 36 months.' },
        maternity: { text: 'Covered after a 72-month (6-year) waiting period. Limits up to ₹25,000 for Caesarean.' },
        newbornCover: { text: 'Covered up to 90 days from birth.' },
        wellness: { text: 'Preventive Health Check-up: Every 2 years. Wellness Discount: Up to 12.5% on renewal.' },
        opdCover: { text: 'Not a primary feature.' },
        otherBenefits: { text: 'AYUSH Hospitalization (up to ₹20,000), Organ Donor Expenses, Bariatric Surgery Cover, Convalescence Benefit.' },
        waitingPeriods: { text: 'Initial: 30 days. Specific Diseases: 24 months. PED: 36 months. Maternity: 72 months.' },
        exclusions: { text: 'Dental treatment, substance abuse, HIV/AIDS, cosmetic surgery.' },
        usps: { text: 'Clear Plan Segmentation. Super No-Claim Bonus in Platinum plan. Recharge Benefit.' },
    },
  },
  {
    id: 'star-super-star',
    insurer: starHealth,
    policyName: 'Star Super Star',
    shortUsp: 'No sub-limits, unlimited restoration, and 50% No Claim Bonus.',
    features: {
      policyType: { text: 'Individual & Family Floater' },
      entryAge: { text: 'Adults (18–65), Children (91 days–25 years)' },
      sumInsured: { text: '₹5L to ₹1 Cr (Silver and Gold variants)' },
      premium: { text: 'Based on the SI amount' },
      hospitalization: { text: 'No sub-limits on any hospitalization expenses' },
      prePostHosp: { text: '90 Days Pre and 180 Days Post' },
      dayCare: { text: 'All day care covered' },
      restoreBenefit: { text: 'Unlimited automatic restoration' },
      cumulativeBonus: { text: '50% No Claim Bonus (up to 100%)' },
      otherBenefits: { text: 'RTA Benefit in Gold plan' },
      chronicDisease: { text: 'Rider for chronic diseases (Quick Shield)' },      maternity: { text: 'Add on feature' },
      newbornCover: { text: 'Add on with maternity' },
      wellness: { text: 'No pre-policy medical check-up required' },
      opdCover: { text: 'Unlimited tele-consultations and dental' },
      waitingPeriods: { text: 'Standard waiting periods apply' },
      exclusions: { text: 'Standard exclusions apply' },
      usps: { text: 'Comprehensive coverage with no sub-limits and high restoration benefits.' },
    },
  },
  {
    id: 'star-super-star-flexi',
    insurer: starHealth,
    policyName: 'Star Super Star Flexi (Secure Variant)',
    shortUsp: 'Works as a top-up plan with flexible deductible and affordable premium.',
    features: {
      policyType: { text: 'Individual & Family Floater (High Deductible Plan)' },
      entryAge: { text: 'Adults (18–65), Children (91 days–25 years)' },
      sumInsured: { text: '₹5L to ₹1 Cr' },
      deductible: { text: '₹25k, ₹50k, ₹1L' },
      hospitalization: { text: 'Works as a top-up plan' },
      prePostHosp: { text: '90 Days Pre and 180 Days Post' },
      premium: { text: 'Flexible deductible + affordable premium' },
      dayCare: { text: 'All day care covered' },
      restoreBenefit: { text: 'Unlimited restoration' },
      cumulativeBonus: { text: '50% No Claim Bonus (up to 100%)' },
      otherBenefits: { text: 'Same RTA and wellness benefits as Super Star' },
      chronicDisease: { text: 'Available with Rider' },
      maternity: { text: 'Yes' },     newbornCover: { text: 'Yes with rider' },
      wellness: { text: 'No medical check-up required' },
      opdCover: { text: 'Unlimited tele-consultations and dental' },
      waitingPeriods: { text: 'Standard waiting periods apply' },
      exclusions: { text: 'Standard exclusions apply' },
      usps: { text: 'Affordable top-up plan with high sum insured and flexible deductibles.' },
    },
  },
];

